[pytest]
testpaths = app/tests
pythonpath = .
python_files = test_*.py
python_functions = test_*
asyncio_mode = auto
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient`:UserWarning
    ignore:'asyncio.iscoroutinefunction' is deprecated:DeprecationWarning
    ignore:No path_separator found in configuration:DeprecationWarning
